baseURL = 'https://blog.b.horn.uk/'
languageCode = 'en-gb'
title = 'bah'
theme = 'archie'
copyright = ""

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=50

rssLimit=50


[params]
	mode = "toggle" # color-mode → light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "making computers do interesting things"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/bahorn"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2
